#!/bin/bash

POSa="$1"
POSx="0"
POSy="0"

set -e

case "$POSa" in

  left)
    POSx="1150"
    ;;
  *)
    echo "error: $POSa not yet enabled"
    echo "Available Positions: 'left'"
    ;;

esac

xrandr --output HDMI1 --scale 2x2
xrandr --output HDMI1 --pos -"$POSx"x0
notify-send -u low "Set Resolution" "Resolution set to Scale 2x2, Position: $POSx x $POSy"
